version: 2
updates:
  - package-ecosystem: "pip" # Define o ecossistema como pip (Python)
    directory: "/" # Localização do arquivo pyproject.toml (na raiz do projeto)
    schedule:
      interval: "daily"
